pipeline:
  name: CI-11556
  identifier: CI11556
  projectIdentifier: ShobhitTest
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: CI11556BitbucketServer
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: ShobhitK8
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.CItestDockerConnectoroRZjRQVrm9
                    image: alpine
                    shell: Sh
                    command: echo "hello"
