pipeline:
  name: CI-11556
  identifier: CI11556
  projectIdentifier: ShobhitTest
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: CI11556BitbucketServer
        repoName: scm/har/naman-test.git
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.CItestDockerConnectoroRZjRQVrm9
                    image: alpine
                    shell: Sh
                    command: echo "hello"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
